# Site settings
title:          LeeU
description:    "My-Blog"
baseurl:
url:            "https://gitjunghyun.github.io"

# Author
author:
  name:         LeeU
  url:          https://github.com/gitjunghyun
  email:        leeu4728@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate # page 분할하는 plugin

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
